# Generated by Django 4.2.4 on 2023-08-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_alter_disciplina_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='area',
            field=models.CharField(max_length=50),
        ),
    ]
