# Generated by Django 4.2.4 on 2023-08-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0003_alter_disciplina_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='tipo',
            field=models.CharField(default='Regular', max_length=50),
        ),
    ]
