# Generated by Django 4.2.4 on 2023-08-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0004_disciplina_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='codigo',
            new_name='curso',
        ),
        migrations.AddField(
            model_name='turma',
            name='SemestresNum',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(choices=[('ENG_ELE', 'Engenharia Elétrica'), ('ENG_COMP', 'Engenharia da Computação'), ('MECANICA', 'Mecânica'), ('RENOVAVEIS', 'Energias Renováveis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='turma',
            name='anoEntrada',
            field=models.IntegerField(),
        ),
    ]
