# Generated by Django 4.2.4 on 2023-08-19 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0005_rename_codigo_turma_curso_turma_semestresnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disciplinas.area'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disciplinas.area'),
        ),
    ]
